// cooped — milestone 2
// Brush core: convex-brush CSG -> mesh -> lit rendering, with a free-fly camera.
// Same dual-target SDL3 + bgfx skeleton as milestone 1; now drawing real geometry
// through a compiled shader (embedded headers, generated natively, see CMakeLists).

#define SDL_MAIN_USE_CALLBACKS 1
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>

#include <bgfx/bgfx.h>
#include <bgfx/platform.h>
#include <bx/math.h>

#include <cstdint>
#include <vector>

#include "brush.h"

// Embedded shader bytecode (committed; generated by the native build for all backends).
#include "shaders/generated/glsl/vs_world.sc.bin.h"
#include "shaders/generated/essl/vs_world.sc.bin.h"
#include "shaders/generated/spirv/vs_world.sc.bin.h"
#include "shaders/generated/glsl/fs_world.sc.bin.h"
#include "shaders/generated/essl/fs_world.sc.bin.h"
#include "shaders/generated/spirv/fs_world.sc.bin.h"

namespace {

bgfx::ShaderHandle makeShader(const uint8_t* data, uint32_t size) {
	return bgfx::createShader(bgfx::copy(data, size));
}

// Pick the right embedded blob for the active renderer (we only generate the backends we run).
bgfx::ProgramHandle createWorldProgram() {
	const uint8_t *vs, *fs;
	uint32_t vsn, fsn;
	switch (bgfx::getRendererType()) {
		case bgfx::RendererType::Vulkan:
			vs = vs_world_spv;  vsn = sizeof(vs_world_spv);
			fs = fs_world_spv;  fsn = sizeof(fs_world_spv);
			break;
		case bgfx::RendererType::OpenGLES:
			vs = vs_world_essl; vsn = sizeof(vs_world_essl);
			fs = fs_world_essl; fsn = sizeof(fs_world_essl);
			break;
		case bgfx::RendererType::OpenGL:
		default:
			vs = vs_world_glsl; vsn = sizeof(vs_world_glsl);
			fs = fs_world_glsl; fsn = sizeof(fs_world_glsl);
			break;
	}
	return bgfx::createProgram(makeShader(vs, vsn), makeShader(fs, fsn), true);
}

struct Mesh {
	bgfx::VertexBufferHandle vbh = BGFX_INVALID_HANDLE;
	bgfx::IndexBufferHandle  ibh = BGFX_INVALID_HANDLE;
	uint32_t numIndices = 0;
	float color[4] = {0.8f, 0.8f, 0.8f, 1.0f};
};

struct Camera {
	bx::Vec3 pos{0.0f, -360.0f, 140.0f};
	float yaw   = bx::kPiHalf;  // look toward +Y
	float pitch = -0.30f;

	bx::Vec3 forward() const {
		const float cp = bx::cos(pitch);
		return {cp * bx::cos(yaw), cp * bx::sin(yaw), bx::sin(pitch)};
	}
};

struct App {
	SDL_Window* window = nullptr;
	uint32_t width = 1280, height = 720;
	bool bgfxInitialized = false;

	bgfx::VertexLayout layout;
	bgfx::ProgramHandle program = BGFX_INVALID_HANDLE;
	bgfx::UniformHandle u_albedo = BGFX_INVALID_HANDLE;
	std::vector<Mesh> meshes;

	Camera cam;
	float mouseDx = 0.0f, mouseDy = 0.0f;
	uint64_t lastTicksNs = 0;
};

Mesh uploadBrush(const Brush& brush, const bgfx::VertexLayout& layout) {
	std::vector<BrushVertex> verts;
	std::vector<uint16_t> indices;
	buildBrushMesh(brush, verts, indices);

	Mesh m;
	m.vbh = bgfx::createVertexBuffer(
	    bgfx::copy(verts.data(), uint32_t(verts.size() * sizeof(BrushVertex))), layout);
	m.ibh = bgfx::createIndexBuffer(
	    bgfx::copy(indices.data(), uint32_t(indices.size() * sizeof(uint16_t))));
	m.numIndices = uint32_t(indices.size());
	m.color[0] = brush.color[0];
	m.color[1] = brush.color[1];
	m.color[2] = brush.color[2];
	m.color[3] = 1.0f;
	return m;
}

void buildScene(App* app) {
	std::vector<Brush> brushes;
	// Floor slab (top surface at z = 0).
	brushes.push_back(makeBox({0, 0, -8}, {512, 512, 8}, 0.45f, 0.47f, 0.50f));
	// A few boxes resting on the floor.
	brushes.push_back(makeBox({0,   0,  32}, {32, 32, 32}, 0.80f, 0.30f, 0.25f));
	brushes.push_back(makeBox({128, 0,  24}, {24, 48, 24}, 0.30f, 0.65f, 0.35f));
	brushes.push_back(makeBox({-128, 96, 40}, {40, 40, 40}, 0.30f, 0.45f, 0.80f));

	// A non-axis-aligned brush: a box with one corner sliced off by a diagonal plane,
	// to show the CSG handles arbitrary half-spaces (not just boxes).
	Brush wedge = makeBox({0, 180, 36}, {56, 56, 36}, 0.78f, 0.70f, 0.30f);
	const bx::Vec3 cut = bx::normalize(bx::Vec3(0.0f, -1.0f, 1.0f));
	wedge.planes.emplace_back(cut, bx::dot(cut, bx::Vec3(0.0f, 124.0f, 72.0f)));
	brushes.push_back(wedge);

	app->meshes.reserve(brushes.size());
	for (const Brush& b : brushes) app->meshes.push_back(uploadBrush(b, app->layout));
}

bool fillPlatformData(SDL_Window* window, bgfx::PlatformData& pd) {
#if defined(__EMSCRIPTEN__)
	(void)window;
	pd.nwh = (void*)"#canvas";
	return true;
#else
	const SDL_PropertiesID props = SDL_GetWindowProperties(window);
	if (props == 0) return false;
#if defined(SDL_PLATFORM_WIN32)
	pd.nwh = SDL_GetPointerProperty(props, SDL_PROP_WINDOW_WIN32_HWND_POINTER, nullptr);
#elif defined(SDL_PLATFORM_MACOS)
	pd.nwh = SDL_GetPointerProperty(props, SDL_PROP_WINDOW_COCOA_WINDOW_POINTER, nullptr);
#elif defined(SDL_PLATFORM_LINUX)
	const char* driver = SDL_GetCurrentVideoDriver();
	if (driver && SDL_strcmp(driver, "wayland") == 0) {
		pd.ndt  = SDL_GetPointerProperty(props, SDL_PROP_WINDOW_WAYLAND_DISPLAY_POINTER, nullptr);
		pd.nwh  = SDL_GetPointerProperty(props, SDL_PROP_WINDOW_WAYLAND_SURFACE_POINTER, nullptr);
		pd.type = bgfx::NativeWindowHandleType::Wayland;
	} else {
		pd.ndt = SDL_GetPointerProperty(props, SDL_PROP_WINDOW_X11_DISPLAY_POINTER, nullptr);
		pd.nwh = (void*)(uintptr_t)SDL_GetNumberProperty(props, SDL_PROP_WINDOW_X11_WINDOW_NUMBER, 0);
	}
#else
	#error "Unsupported platform"
#endif
	return pd.nwh != nullptr;
#endif
}

}  // namespace

SDL_AppResult SDL_AppInit(void** appstate, int, char**) {
	if (!SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS)) {
		SDL_Log("SDL_Init failed: %s", SDL_GetError());
		return SDL_APP_FAILURE;
	}

	App* app = new App();
	*appstate = app;

	app->window = SDL_CreateWindow("cooped — milestone 2", (int)app->width, (int)app->height,
	                               SDL_WINDOW_RESIZABLE | SDL_WINDOW_HIGH_PIXEL_DENSITY);
	if (!app->window) {
		SDL_Log("SDL_CreateWindow failed: %s", SDL_GetError());
		return SDL_APP_FAILURE;
	}

	int pw = 0, ph = 0;
	SDL_GetWindowSizeInPixels(app->window, &pw, &ph);
	app->width = (uint32_t)pw;
	app->height = (uint32_t)ph;

	bgfx::renderFrame();  // single-threaded

	bgfx::Init init;
	init.type = bgfx::RendererType::Count;
	init.resolution.width = app->width;
	init.resolution.height = app->height;
	init.resolution.reset = BGFX_RESET_VSYNC;
	if (!fillPlatformData(app->window, init.platformData)) return SDL_APP_FAILURE;
	if (!bgfx::init(init)) return SDL_APP_FAILURE;
	app->bgfxInitialized = true;

	bgfx::setViewClear(0, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH, 0x202830ff, 1.0f, 0);
	bgfx::setDebug(BGFX_DEBUG_TEXT);

	app->layout.begin()
	    .add(bgfx::Attrib::Position, 3, bgfx::AttribType::Float)
	    .add(bgfx::Attrib::Normal, 3, bgfx::AttribType::Float)
	    .end();

	app->program = createWorldProgram();
	app->u_albedo = bgfx::createUniform("u_albedo", bgfx::UniformType::Vec4);

	buildScene(app);

	SDL_SetWindowRelativeMouseMode(app->window, true);
	app->lastTicksNs = SDL_GetTicksNS();

	SDL_Log("bgfx renderer: %s", bgfx::getRendererName(bgfx::getRendererType()));
	return SDL_APP_CONTINUE;
}

SDL_AppResult SDL_AppEvent(void* appstate, SDL_Event* event) {
	App* app = static_cast<App*>(appstate);
	switch (event->type) {
		case SDL_EVENT_QUIT:
			return SDL_APP_SUCCESS;
		case SDL_EVENT_KEY_DOWN:
			if (event->key.key == SDLK_ESCAPE) return SDL_APP_SUCCESS;
			break;
		case SDL_EVENT_MOUSE_MOTION:
			app->mouseDx += event->motion.xrel;
			app->mouseDy += event->motion.yrel;
			break;
		case SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED:
			app->width = (uint32_t)event->window.data1;
			app->height = (uint32_t)event->window.data2;
			bgfx::reset(app->width, app->height, BGFX_RESET_VSYNC);
			break;
		default:
			break;
	}
	return SDL_APP_CONTINUE;
}

SDL_AppResult SDL_AppIterate(void* appstate) {
	App* app = static_cast<App*>(appstate);

	const uint64_t now = SDL_GetTicksNS();
	float dt = float(double(now - app->lastTicksNs) / 1.0e9);
	app->lastTicksNs = now;
	if (dt > 0.1f) dt = 0.1f;

	// Mouse look.
	const float sens = 0.0025f;
	app->cam.yaw += app->mouseDx * sens;
	app->cam.pitch -= app->mouseDy * sens;
	app->cam.pitch = bx::clamp(app->cam.pitch, -1.5f, 1.5f);
	app->mouseDx = app->mouseDy = 0.0f;

	// Free-fly movement (WASD + space/ctrl), shift to sprint.
	const bool* keys = SDL_GetKeyboardState(nullptr);
	const bx::Vec3 fwd = app->cam.forward();
	const bx::Vec3 worldUp{0.0f, 0.0f, 1.0f};
	const bx::Vec3 right = bx::normalize(bx::cross(worldUp, fwd));
	float speed = (keys[SDL_SCANCODE_LSHIFT] ? 700.0f : 250.0f) * dt;
	bx::Vec3 move{0.0f, 0.0f, 0.0f};
	if (keys[SDL_SCANCODE_W]) move = bx::add(move, fwd);
	if (keys[SDL_SCANCODE_S]) move = bx::sub(move, fwd);
	if (keys[SDL_SCANCODE_D]) move = bx::add(move, right);
	if (keys[SDL_SCANCODE_A]) move = bx::sub(move, right);
	if (keys[SDL_SCANCODE_SPACE]) move = bx::add(move, worldUp);
	if (keys[SDL_SCANCODE_LCTRL]) move = bx::sub(move, worldUp);
	if (bx::length(move) > 0.0f) app->cam.pos = bx::add(app->cam.pos, bx::mul(bx::normalize(move), speed));

	// Camera matrices (Z-up).
	float view[16], proj[16];
	const bx::Vec3 at = bx::add(app->cam.pos, fwd);
	bx::mtxLookAt(view, app->cam.pos, at, worldUp);
	const float aspect = float(app->width) / float(app->height);
	bx::mtxProj(proj, 60.0f, aspect, 1.0f, 12000.0f, bgfx::getCaps()->homogeneousDepth);

	bgfx::setViewRect(0, 0, 0, (uint16_t)app->width, (uint16_t)app->height);
	bgfx::setViewTransform(0, view, proj);
	bgfx::touch(0);

	// No cull bit set == no backface culling (brush winding isn't guaranteed yet).
	const uint64_t state = BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A | BGFX_STATE_WRITE_Z |
	                       BGFX_STATE_DEPTH_TEST_LESS;
	for (const Mesh& m : app->meshes) {
		bgfx::setVertexBuffer(0, m.vbh);
		bgfx::setIndexBuffer(m.ibh);
		bgfx::setUniform(app->u_albedo, m.color);
		bgfx::setState(state);
		bgfx::submit(0, app->program);
	}

	bgfx::dbgTextClear();
	bgfx::dbgTextPrintf(1, 1, 0x0f, "cooped - milestone 2 (brush core)");
	bgfx::dbgTextPrintf(1, 2, 0x0a, "renderer: %s | brushes: %zu",
	                    bgfx::getRendererName(bgfx::getRendererType()), app->meshes.size());
	bgfx::dbgTextPrintf(1, 3, 0x0e, "WASD + mouse to fly, space/ctrl up/down, shift sprint, esc quit");

	bgfx::frame();
	return SDL_APP_CONTINUE;
}

void SDL_AppQuit(void* appstate, SDL_AppResult) {
	App* app = static_cast<App*>(appstate);
	if (!app) return;
	if (app->bgfxInitialized) {
		for (const Mesh& m : app->meshes) {
			if (bgfx::isValid(m.vbh)) bgfx::destroy(m.vbh);
			if (bgfx::isValid(m.ibh)) bgfx::destroy(m.ibh);
		}
		if (bgfx::isValid(app->u_albedo)) bgfx::destroy(app->u_albedo);
		if (bgfx::isValid(app->program)) bgfx::destroy(app->program);
		bgfx::shutdown();
	}
	if (app->window) SDL_DestroyWindow(app->window);
	delete app;
	SDL_Quit();
}
